# Generated by Django 4.2.1 on 2023-05-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_created_at_alter_book_published_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='isbn_13',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
