# Generated by Django 4.2.1 on 2023-05-09 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
        ('books', '0004_rename_isbn_book_isbn_13_book_isbn_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelves.shelf'),
        ),
    ]
