# Generated by Django 4.2.1 on 2023-05-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tags',
            new_name='topics',
        ),
    ]
