# Generated by Django 4.2.1 on 2023-05-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_tags_book_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file_url',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books'),
        ),
    ]
