# Generated by Django 4.2.1 on 2023-05-10 17:46

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('books', '0008_remove_book_file_url_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.get_book_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=books.models.get_book_upload_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='topics',
            field=models.ManyToManyField(blank=True, to='topics.topic'),
        ),
    ]
