// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnRI5eWvvfdyuRgW5HxedxSdHPc76ftp4',
    appId: '1:344941864747:web:a807275c80e8066959876e',
    messagingSenderId: '344941864747',
    projectId: 'papyrus-6b9ba',
    authDomain: 'papyrus-6b9ba.firebaseapp.com',
    storageBucket: 'papyrus-6b9ba.firebasestorage.app',
    measurementId: 'G-P0HMMVC1ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtl08RDSVubnlTOVb9y3KddUtPFn9j4VI',
    appId: '1:344941864747:android:4aa61636fec0fbcd59876e',
    messagingSenderId: '344941864747',
    projectId: 'papyrus-6b9ba',
    storageBucket: 'papyrus-6b9ba.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqGr3it1tHnbacklPwgZX4l1g1u8-JDBM',
    appId: '1:344941864747:ios:e9e3b80c426b52f459876e',
    messagingSenderId: '344941864747',
    projectId: 'papyrus-6b9ba',
    storageBucket: 'papyrus-6b9ba.firebasestorage.app',
    androidClientId:
        '344941864747-86upqg83n160mjavogdkt5ust3u0hf9p.apps.googleusercontent.com',
    iosClientId:
        '344941864747-nvakkh3s8hdhd4gc452ope1vk550c6rj.apps.googleusercontent.com',
    iosBundleId: 'com.papyrus.papyrus',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqGr3it1tHnbacklPwgZX4l1g1u8-JDBM',
    appId: '1:344941864747:ios:e9e3b80c426b52f459876e',
    messagingSenderId: '344941864747',
    projectId: 'papyrus-6b9ba',
    storageBucket: 'papyrus-6b9ba.firebasestorage.app',
    androidClientId:
        '344941864747-86upqg83n160mjavogdkt5ust3u0hf9p.apps.googleusercontent.com',
    iosClientId:
        '344941864747-nvakkh3s8hdhd4gc452ope1vk550c6rj.apps.googleusercontent.com',
    iosBundleId: 'com.papyrus.papyrus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnRI5eWvvfdyuRgW5HxedxSdHPc76ftp4',
    appId: '1:344941864747:web:2e13e41050af3d8d59876e',
    messagingSenderId: '344941864747',
    projectId: 'papyrus-6b9ba',
    authDomain: 'papyrus-6b9ba.firebaseapp.com',
    storageBucket: 'papyrus-6b9ba.firebasestorage.app',
    measurementId: 'G-BLJLRW8T4R',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAnRI5eWvvfdyuRgW5HxedxSdHPc76ftp4',
    appId: '1:344941864747:web:b373710a395199e859876e',
    messagingSenderId: '344941864747',
    projectId: 'papyrus-6b9ba',
    authDomain: 'papyrus-6b9ba.firebaseapp.com',
    storageBucket: 'papyrus-6b9ba.firebasestorage.app',
    measurementId: 'G-H2DBJRT8CV',
  );
}
