// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-8hZptr95g6pacDck8I_48wAxyRGEjT4',
    appId: '1:789494478936:web:ca0dcabe273e8a448b322d',
    messagingSenderId: '789494478936',
    projectId: 'papyrus-library-manager',
    authDomain: 'papyrus-library-manager.firebaseapp.com',
    storageBucket: 'papyrus-library-manager.appspot.com',
    measurementId: 'G-4JXT4NE70Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABqcOAVutKXuslOYo4ZcN_rklCMUaBD5M',
    appId: '1:789494478936:android:1a5ded1a77cadbc08b322d',
    messagingSenderId: '789494478936',
    projectId: 'papyrus-library-manager',
    storageBucket: 'papyrus-library-manager.appspot.com',
  );
}
